databases:
  - name: nightroutine_DB
    databaseName: nightroutine_db
    user: nightroutine
    region: singapore

services:
  - type: web
    name: nightroutine
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nightroutine_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false


